### ISSUE TITLE
Compliance with PSR-2 and/or PSR-12?

### ISSUE THREAD

**Issue by niconoe-** [phpstan/extension-installer#8]
Hi there, and first of all, thank you for this awesome work!

When I wanted to propose a new pull request, I found that your script is following a coding standard that is not in compliance with the [PSR-2](https://www.php-fig.org/psr/psr-2/) nor the incoming [PSR-12](https://github.com/php-fig/fig-standards/blob/master/proposed/extended-coding-style-guide.md).

Is this something you did by choice (to not rely on those PSRs)?
On other hand, if you're interested in to follow those standards (and being more strict by continuing to follow your current rules that are not in conflict with PSRs), I can provide a PR for that.

Thanks again

**Comment by ondrejmirtes** [comment]
Hi, I always welcome improvement one step at a time. This is a very small repo where it doesn't matter, but feel free to open PR with a single new sniff added to phpcs.xml in `phpstan/phpstan`.

I'm more interested in strict code checking (which was the biggest inspiration for slevomat/coding-standard) rather than following standards, but I'd like to see what you have in mind.
